trigger:
- main

pool:
  vmImage: 'ubuntu-16.04'

variables:
  imageName: 'ubuntu'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile


  
