trigger:
- main

pool:
  vmImage: 'ubuntu-1604'

variables:
  imageName: 'ubuntu:test'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile


  
